// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Title field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título da categoria
   * - **API ID Path**: category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Page Description field in *Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da página
   * - **API ID Path**: category.page_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_description: prismic.RichTextField;

  /**
   * Hero Image field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Category Key field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Pasta de fallback
   * - **API ID Path**: category.category_key
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_key: prismic.KeyTextField;

  /**
   * Card Description field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Descrição do Card
   * - **API ID Path**: category.card_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_description: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *Work → Gallery Images*
 */
export interface WorkDocumentDataGalleryImagesItem {
  /**
   * Image field in *Work → Gallery Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Alt Text field in *Work → Gallery Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto alternativo da imagem
   * - **API ID Path**: work.gallery_images[].image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;
}

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Work Key field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Chave estável (ex: casa1-uberlandia) - para fallback com pastas
   * - **API ID Path**: work.work_key
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  work_key: prismic.KeyTextField;

  /**
   * Title field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: Casa Uberlândia
   * - **API ID Path**: work.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do trabalho
   * - **API ID Path**: work.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Category field in *Work*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: ContentRelationshipFieldWithData<
    [{ id: "category"; fields: ["title"] }]
  >;

  /**
   * Gallery Images field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.gallery_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery_images: prismic.GroupField<
    Simplify<WorkDocumentDataGalleryImagesItem>
  >;

  /**
   * Gallery Fallback Alt field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Alt padrão quando não houver alt por imagem
   * - **API ID Path**: work.gallery_image_alt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gallery_image_alt: prismic.KeyTextField;

  /**
   * External Link field in *Work*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link externo (opcional)
   * - **API ID Path**: work.external_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  external_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Order field in *Work*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Ordem dentro da categoria (0, 1, 2...)
   * - **API ID Path**: work.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  order: prismic.NumberField;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes = CategoryDocument | WorkDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoryDocument,
      CategoryDocumentData,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataGalleryImagesItem,
      AllDocumentTypes,
    };
  }
}
